#!/bin/bash
# ----------------------------------------------------------------------
#    Copyright (c) 2014
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 3 of the GNU General Public
#    License published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
# ----------------------------------------------------------------------
# Authors:
#  Alex V Kotelnikov (aka gudron) <gudron@gudron.me>
#
# Repository:
#  https://github.com/gudron/vhotsy
#
# /usr/local/bin/vhosty-delete

virtualHostsPath=""
databaseType=""
databaseAccessUser=""
databaseAccessPassword=""
databaseHost=""
hostPerUser=false
owner=""

userName=""
containerName=""
homePath=""
rootPath=""

usage() {
	sn=`basename $0`

	echo "USAGE: $sn -h <HOST_NAME> -D <DATABASE_TYPE> -u <DATABASE_USER>\
		-U <PASSWORD_FOR_DATABASE_USER>"

	echo "USAGE: $sn --host <HOST_NAME> --database-password <DATABASE_PASSWORD>"	
	echo "USAGE: $sn -h <HOST_NAME>"
	echo -e "Options:"
	echo -e "\t-h | --host <HOST_NAME>\tName of virtual host.\tExample:\
 example.dev,example.loc"

	echo -e "\t-D | --database-type <DATABASE_TYPE>\tWhat database u want use.\
 Available: mysql"

	echo -e "\t-H | --database-host <DATABASE_SERVER_ADRESS>\tDatabase server\
 name or adress. Example: 127.0.0.1"

	echo -e "\t-u | --database-access-user <USER_NAME_TO_DATABASE_ACCESS>\tUser\
 name who can create databse and grants priveleges. Example: root."

	echo -e "\t-U | --database-access-password\
 <USER_PASSWORD_TO_DATABASE_ACCESS>\tPassword for user who can create\
 database and grants priveleges. Example: superSecredPaswword."
 
}

printError() {
	echo "[!] Invalid option" && usage && exit 1
}

deleteJailRoot() {
	deleteHome() {
		rm -rf $homePath
	}

	deleteHome
	rm -rf $rootPath
	sed -i "/$hostname/d" "$virtualHostsPath"/hostlist 
}

main () {
	source ./vhosty-helpers
	containerName=$(findHostByName $hostname $virtualHostsPath)

	rootPath="$virtualHostsPath"/containers/"$containerName"
	homePath="$rootPath"/home

	cfg_parser "$rootPath"/hostconfig.ini
	cfg.section.main

	deleteJailRoot
	rm -f "$virtualHostsPath"/"$hostname"
}

TEMP=`getopt -o h:D:H:j: -l host:,database-host:,jail-roots-path: -n 'vhosty.sh' -- "$@"`

if [ $? != 0 ] ; then printError ; fi

eval set -- "$TEMP"
while true ; do
	case "$1" in
		-h|--host ) 
			hostname="$2" ; shift 2 ;;
		
		-H|--database-host )
			databaseHost="$2" ; shift 2 ;;			

		-j|--jail-roots-path )
			virtualHostsPath="$2" ; shift 2 ;;

		-- ) shift ; break ;;
		* ) printError;;
	esac
done

if [ "$hostname" != "" ]
then
	main
else
	printError
fi