#!/bin/bash
# ----------------------------------------------------------------------
#    Copyright (c) 2014
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 3 of the GNU General Public
#    License published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
# ----------------------------------------------------------------------
# Authors:
#  Alex V Kotelnikov (aka gudron) <gudron@gudron.me>
#
# Repository:
#  https://github.com/gudron/vhotsy
#
# /usr/local/bin/vhosty-delete

virtualHostsPath=""
databaseType=""
databaseAccessUser=""
databaseAccessPassword=""
databaseHost=""
dataBaseName=""
databaseUserName=""
hostPerUser=false
owner=""

userName=""
containerName=""
homePath=""
rootPath=""

usage() {
	sn=`basename $0`

	echo "USAGE: $sn -h <HOST_NAME> -j <PATH_TO_VHOSTS_PARENT_DIR>"
	echo -e "Options:"
	echo -e "\t-h | --host <HOST_NAME>\tName of virtual host.\tExample:\
 example.dev,example.loc"
 
}

printError() {
	echo "[!] Invalid option" && usage && exit 1
}

deleteJailRoot() {
	deleteHome() {
		rm -rf $homePath
	}

	deleteHome
	rm -rf $rootPath
	sed -i "/$hostname/d" "$virtualHostsPath"/hostlist 
}

deleteDatabase() {
	source ./vhosty-database

	comand="$databaseType"_delete_db_user
	$comand $dataBaseName $databaseHost $databaseAccessPassword $databaseUserName

	comand="$databaseType"_delete_db
	$comand $dataBaseName $databaseHost $databaseAccessPassword
}

run () {
	rootPath="$virtualHostsPath"/containers/"$containerName"
	homePath="$rootPath"/home

	#loading host config
	cfg_parser "$rootPath"/hostconfig.ini "cfg"
	cfg.section.main

	dataBaseName=$DB_NAME
	databaseHost=$DB_HOST
	databaseUserName=$DB_USER_NAME

	databaseType=$DB_TYPE

	maincfg.section."$databaseType"

	databaseAccessUser="$DB_USER"
	databaseAccessPassword="$DB_PASS"

	deleteDatabase
	deleteJailRoot
	

	rm -f "$virtualHostsPath"/"$hostname"
}

main () {
	source ./vhosty-helpers

	#loading main vhosty config
	cfg_parser "$VHOSTY_CONFIG_FILE_PATH" "maincfg"
	#parse main vhosty database config
	maincfg.section.main
	virtualHostsPath="$WEB_CONF_ROOT"
	echo $hostname $virtualHostsPath
	containerName=$(helper_findHostByName $hostname $virtualHostsPath)

	if [ "$containerName" == "" ] 
	then
		error_printHostNotFound
	else
		run
	fi
}

TEMP=`getopt -o h: -l host: -n 'vhosty.sh' -- "$@"`

if [ $? != 0 ] ; then printError ; fi

eval set -- "$TEMP"
while true ; do
	case "$1" in
		-h|--host ) 
			hostname="$2" ; shift 2 ;;

		-- ) shift ; break ;;
		* ) printError;;
	esac
done

if [ "$hostname" != "" ]
then
	main
else
	printError
fi