#!/bin/bash
# ----------------------------------------------------------------------
#    Copyright (c) 2014
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 3 of the GNU General Public
#    License published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
# ----------------------------------------------------------------------
# Authors:
#  Alex V Kotelnikov (aka gudron) <gudron@gudron.me>
#
# Repository:
#  https://github.com/gudron/vhotsy
#
# /usr/local/bin/vhosty-delete

virtualHostsPath=""
databaseType=""
databaseAccessUser=""
databaseAccessPassword=""
databaseHost=""
hostPerUser=false
owner=""

userName=""
containerName=""
homePath=""
rootPath=""

usage() {
	sn=`basename $0`

	echo "USAGE: $sn -c -h <HOST_NAME> -P <PASSWORD> -t <WEB_SERVER_CONFIG_TEMPLATE> -u <DATABASE_USER> -U <PASSWORD_FOR_DATABASE_USER>"
	echo "USAGE: $sn -u --host <HOST_NAME> --database-password <DATABASE_PASSWORD>"	
	echo "USAGE: $sn -d -h <HOST_NAME>"
	echo -e "Options:"
	echo -e "\t-h | --host <HOST_NAME>\tName of virtual host.\tExample: example.dev,example.loc"
	echo -e "\t-P | --password Set password on database and system user"
	echo -e "\t-p | --database-password Set password on database and system user"
	echo -e "\t-t | --template <WEB_SERVER_CONFIG_TEMPLATE>\tName of config template for webserver.\n\tExample: wolfcms,yii,cohana. Full list in https://github.com/gudron/nginxconfy"
	echo -e "\t-j | --jail-roots-path <PATH_TO_VHOSTS_PARENT_DIR>\tPath to parent directory of all virtual hosts. Example: /var/www/"
	echo -e "\t-D | --database-type <DATABASE_TYPE>\tWhat database u want use. Available: mysql"
	echo -e "\t-H | --database-host <DATABASE_SERVER_ADRESS>\tDatabase server name or adress. Example: 127.0.0.1"
	echo -e "\t-u | --database-access-user <USER_NAME_TO_DATABASE_ACCESS>\tUser name who can create databse and grants priveleges. Example: root."
	echo -e "\t-U | --database-access-password <USER_PASSWORD_TO_DATABASE_ACCESS>\tPassword for user who can create database and grants priveleges. Example: superSecredPaswword."
	echo -e "\t--host-pre-user\t Using one host one user structure."
	echo -e "\t--owner\t If not host per user, then using owner of files and folders."
}