#!/bin/bash
# ----------------------------------------------------------------------
#	Copyright (c) 2014
#
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of version 3 of the GNU General Public
#	License published by the Free Software Foundation.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
# ----------------------------------------------------------------------
# Authors:
#	Alex V Kotelnikov (aka gudron) <gudron@gudron.me>
#
#
# Repository:
#	https://github.com/gudron/vhotsy
#
# /usr/local/bin/vhosty-update

virtualHostsPath=""
databaseType=""
databaseAccessUser=""
databaseAccessPassword=""
databaseHost=""
dataBaseName=""
databaseUserName=""
hostPerUser=false
owner=""

userName=""
containerName=""
homePath=""
rootPath=""


run () {

}

main () {
	source ./vhosty-helpers

	#loading main vhosty config
	cfg_parser "$VHOSTY_CONFIG_FILE_PATH" "maincfg"
	#parse main vhosty database config
	maincfg.section.main
	virtualHostsPath="$WEB_CONF_ROOT"
	echo $hostname $virtualHostsPath
	containerName=$(helper_findHostByName $hostname $virtualHostsPath)

	if [ "$containerName" == "" ] 
	then
		error_printHostNotFound
	else
		run
	fi
}

TEMP=`getopt -o h:n: -l host:new-host: -n 'vhosty.sh' -- "$@"`

if [ $? != 0 ] ; then printError ; fi

eval set -- "$TEMP"
while true ; do
	case "$1" in
		-h|--host ) 
			hostname="$2" ; shift 2 ;;
		-n|--new-host ) 
			hostname="$2" ; shift 2 ;;


		-- ) shift ; break ;;
		* ) printError;;
	esac
done

if [ "$hostname" != "" ]
then
	main
else
	printError
fi